### ISSUE TITLE
BSD Coreutils fails to bootstrap 

### ISSUE THREAD

**Issue by techdragon** [sgleizes/xsh#2]
```
MacBook-Pro:~ techdragon$ xsh bootstrap
+ [bash] creating directory: /Users/techdragon/.config/shell/bash
+ [bash] linking shell runcoms
ln: illegal option -- -
usage: ln [-Ffhinsv] source_file [target_file]
       ln [-Ffhinsv] source_file ... target_dir
       link source_file target_file
ln: illegal option -- -
usage: ln [-Ffhinsv] source_file [target_file]
       ln [-Ffhinsv] source_file ... target_dir
       link source_file target_file
ln: illegal option -- -
usage: ln [-Ffhinsv] source_file [target_file]
       ln [-Ffhinsv] source_file ... target_dir
       link source_file target_file
ln: illegal option -- -
usage: ln [-Ffhinsv] source_file [target_file]
       ln [-Ffhinsv] source_file ... target_dir
       link source_file target_file
+ [bash] creating default init file: bash/init.bash
+ [bash] creating default module runcom: bash/core/@interactive.bash
```

That illegal option looks like failure due to not using the GNU tools but the BSD ones.

One tactic I've used is to use platform detection in combination with function wrappers, by assignment of the correct function wrapper to the function used throughout the code in order to allow workarounds and alternative options to be used to support BSD coreutils, or alternative commands in the case of homebrew coreutils... this will ensure that its possible to get the necessary functionality is provided regardless of the OS and coreutils in use.

I'm writing this up for my own needs, since I want cross platform use, ideally with actual BSD coreutil support, but I also want to get up and running sooner, so I'm building a 'needs homebrew installed coreutils on macos' version of this functionality that I'm happy submitting as a PR. I also intend to add annotations with respect for `shellcheck` as I find it invaluable in keeping my shell scripting from accidentally using non-posix behaviour without knowing it.

**Comment by sgleizes** [comment]
Thank you for perfectly answering [this call for help](https://github.com/sgleizes/xsh#dependencies).

Regarding shellcheck annotations, there are already a few, but I had indeed left that last part about incompatible POSIX usage pending. It seems now that [shellcheck provides a way](https://github.com/koalaman/shellcheck/wiki/SC2039) to disable more specific warnings, so I've added what was coherent with the assumptions I made during development. See [this commit](https://github.com/sgleizes/xsh/commit/631b416c6ab3a3a289725c03b47bb71857c2ad51).

Looking forward to your PR adding support for BSD platforms!

**Comment by sgleizes** [comment]
So, macOS support was added in [0.3.1](https://github.com/sgleizes/xsh/compare/v0.3.0...v0.3.1) and right now I don't plan on adding support for other BSD systems. It seems like a significant amount of work and added complexity for little benefit.
If one day there's a BSD user asking for it, I'll maybe reconsider...
