### ISSUE TITLE
XSH_RUNCOM_PREFIX

### ISSUE THREAD

**Issue by amsitlab** [sgleizes/xsh#6]
module runcom in `$XSH_CONFIG_DIR/<shell-variant>/<module>/` not loded, when you set `XSH_RUNCOM_PREFIX=.` in ~/.bash_profile, ~/.profile, etc..

**Comment by sgleizes** [comment]
Thanks for reporting, there's indeed a bug with `XSH_RUNCOM_PREFIX=.` that prevents hidden files from being matched properly.

However, it should already work if your module runcoms are not hidden files, for example: `module.interactive.bash`
Note that in order for `XSH_RUNCOM_PREFIX=.` to be picked up properly, it needs to be set as described in the README:

> You can change the special character for runcom files by setting the environment variable XSH_RUNCOM_PREFIX (default @). Like XSH_DIR this should be set before you user's login shell is started. Alternatively, it can be set on a per-shell basis in the [xsh initialization file](https://github.com/sgleizes/xsh#initialization-file) for that shell.

Let me know if that solves your problem, or if you would expect hidden files to be matched as well.

**Comment by amsitlab** [comment]
I think this is enough (for me), but you should include about it in readme.md to avoid the same problem.
or maybe you want to use a combination of `find` and `sort -z` to patch problems.

Thank for your great jobs.

**Comment by sgleizes** [comment]
Sorry for the delay, I've been quite busy.

Thanks for the suggestion but I want to avoid spawning additional processes for performance reasons.
I've fixed it on the latest master, hidden files should now properly be picked up and loaded like the others.

I'm closing this, let me know if you have additional issues.
